# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f2816da3b4d30d88771ed5a7d388fee"
name = "stockwise"
handle = "stockwise-2"
application_url = "https://itself-absent-commented-proposal.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/api/webhooks/app_scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app_uninstalled"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://itself-absent-commented-proposal.trycloudflare.com/auth/callback",
  "https://itself-absent-commented-proposal.trycloudflare.com/auth/shopify/callback",
  "https://itself-absent-commented-proposal.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
